global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - alertmanager: 9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    # metrics_path: /metrics
    # honor_labels: false
    # honor_timestamps: true
    # scheme: http
    # follow_redirects: true
    # body_size_limit: 0
    # sample_limit: 0
    # label_limit: 0
    # label_name_length_limit: 0
    # label_value_length_limit: 0
    # target_limit: 0
    static_configs:
      - targets: ["prom:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:9091"]

  - job_name: "rust_ws_app"
    static_configs:
      - targets: ["rust_ws_app:8000"]
    # metrics_path: /

  - job_name: "python_ws_app"
    static_configs:
      - targets: ["python_ws_app:8002"]
