{
 "title": "WebSocket Server: Rust vs Python",
 "description": "Rust vs Python ws server",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WS connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ws_connections", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Python broadcast p(95)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ws_broadcast_duration_seconds_bucket{job=\"python_ws_app\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rust broadcast p(95)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ws_broadcast_duration_seconds_bucket{job=\"rust_ws_app\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WS closed connection errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ws_conn_closed_erros_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "WS connections total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "all_ws_connections_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\", name=~\".*[rust|python]_ws_app.*\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", name=~\".*[rust|python]_ws_app.*\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Rust broadcast latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(ws_broadcast_duration_seconds_bucket{job=\"rust_ws_app\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rust message handling latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(ws_message_handling_duration_seconds_bucket{job=\"rust_ws_app\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python broadcast latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(ws_broadcast_duration_seconds_bucket{job=\"python_ws_app\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python message handling latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(ws_message_handling_duration_seconds_bucket{job=\"python_ws_app\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}