FROM grafana/grafana

ADD grafana.ini /etc/grafana/
ADD datasources.yml /etc/grafana/provisioning/datasources/
ADD dashboard.json /var/lib/grafana/dashboards/
ADD default.yaml /etc/grafana/provisioning/dashboards/
